### ISSUE TITLE
PKGi+ icon causes integrity check to fail

### ISSUE THREAD

**Issue by Hydrogen8** [JamesIsWack/PKGi-plus#1]
The icon included in this version of PKGi+ causes the integrity check to fail and the application never launches.

**Comment by kernaltrap8** [comment]
yes, this is due to checksum checks in the EBOOT.ELF. i will have to recompile PKGi from source with the new icon in order for it to boot correctly (and edit some `.h` files beforehand). thank you for making the issue.

**Comment by Hydrogen8** [comment]
The issue has not been fixed.
